version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "master"
    assignees:
      - "ii1818nn"

  - package-ecosystem: "gomod"
    directory: "/packages/pkg-inf-terraform-provider-abstract"
    schedule:
      interval: "weekly"
    target-branch: "master"
    assignees:
      - "ii1818nn"
