name: pkg-inf-terraform-provider-abstract-policy

on:
  pull_request:
    branches: [master]
    paths:
      - packages/pkg-inf-terraform-provider-abstract/**

jobs:
  pkg-inf-terraform-provider-abstract-policy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: stable
          cache-dependency-path: packages/pkg-inf-terraform-provider-abstract/go.sum

      - uses: golangci/golangci-lint-action@v7
        with:
          version: v2.1.6
          working-directory: packages/pkg-inf-terraform-provider-abstract

      - run: make pkg-inf-terraform-provider-abstract-build

      - run: make pkg-inf-terraform-provider-abstract-test
